---
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: cosmo
params: 
  topDir: 
    value: 'data/example/'
  fusion_method:
    value: 'both'
  set_title:
    value: 'Patient Report'
  snv_pattern:
    value: NULL
editor_options: 
  chunk_output_type: console
---
---
title: `r params$set_title`
---

```{r include=FALSE, echo=FALSE}
knitr::opts_chunk$set(comment = NA)
```

```{r load_libraries}
source('code/load_libraries.R')
```

```{r read_data}
# read input files
source("code/readData.R")
topDir <- params$topDir
fusion_method <- params$fusion_method
snv_pattern <- params$snv_pattern
readData(topDir = topDir, 
         fusion_method = fusion_method, 
         snv_pattern = snv_pattern)
```

```{r call_driver}
# call driver to load other libraries/code
source("code/driver.R")
```

Transcriptomic Alterations (P2)
===
Row {data-height=700}
---

### Transcriptome Alterations
    
```{r plot_genes}
if(exists('expData')){
  ggplotly(plotGenes()); 
}
```

### Pathway Alterations

```{r plot_pathway}
#Bar chart of genes
if(exists('expData')){
  ggplotly(plotPathway());
}
```
